import type { Metadata } from "next";
import Link from "next/link";
import { Card } from "@/components/ui/Card";
import {
  ScrollText,
  UserCheck,
  Sparkles,
  Bot,
  Ban,
  AlertTriangle,
  RefreshCw,
  Mail,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms that govern your use of Musemint, the memory layer for ideas you want to build.",
};

const LAST_UPDATED = "May 29, 2026";
const CONTACT_EMAIL = "privacy@musemint.app";

function Section({
  icon: Icon,
  title,
  children,
}: {
  icon: React.ComponentType<{ className?: string }>;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="space-y-3">
      <h2 className="flex items-center gap-2 text-lg font-semibold tracking-tight text-ink">
        <Icon className="h-5 w-5 text-accent" />
        {title}
      </h2>
      <div className="space-y-3 text-sm leading-relaxed text-ink-mute">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl space-y-8">
      <header className="space-y-3">
        <div className="flex items-center gap-2 text-xs font-medium uppercase tracking-wide text-accent">
          <ScrollText className="h-4 w-4" />
          Terms
        </div>
        <h1 className="text-3xl font-semibold tracking-tight text-ink">Terms of Service</h1>
        <p className="text-sm text-ink-mute">Last updated {LAST_UPDATED}</p>
        <p className="text-sm leading-relaxed text-ink-mute">
          These terms govern your use of Musemint. By using the app you agree to them. If you do not
          agree, do not use the app.
        </p>
      </header>

      <Card className="space-y-7">
        <Section icon={Sparkles} title="What Musemint does">
          <p>
            Musemint is a personal tool that saves ideas you capture — posts, videos, screenshots,
            links, and notes — then classifies, scores, and helps you turn them into project briefs
            and shipping work. It is provided for your own personal and productivity use.
          </p>
        </Section>

        <Section icon={UserCheck} title="Your responsibilities">
          <p>
            You are responsible for the content you save and for having the right to save it. Use
            Musemint in compliance with applicable laws and with the terms of any platform the
            content originates from. Do not use it to infringe others’ rights or to store unlawful
            material.
          </p>
          <p>
            Do not save secrets, passwords, financial account numbers, or government IDs. Musemint is
            built for ideas, not credentials.
          </p>
        </Section>

        <Section icon={Bot} title="AI-generated output">
          <p>
            Summaries, categories, scores, and build packs are generated by AI and may be inaccurate
            or incomplete. Treat them as drafts to review, not as professional, legal, financial, or
            investment advice. You are responsible for verifying output before relying on it.
          </p>
          <p>
            AI features depend on third-party providers you configure (such as Google, OpenAI,
            Anthropic, or Mistral). Their availability and behavior are outside Musemint’s control.
          </p>
        </Section>

        <Section icon={Ban} title="Acceptable use">
          <p>
            Do not attempt to break, overload, reverse-engineer, or gain unauthorized access to the
            service or its infrastructure. Do not use Musemint to scrape private data or to violate
            any platform’s terms. Musemint does not log into third-party accounts on your behalf.
          </p>
        </Section>

        <Section icon={AlertTriangle} title="No warranty and limitation of liability">
          <p>
            Musemint is provided “as is,” without warranties of any kind, express or implied. To the
            maximum extent permitted by law, the maintainers are not liable for any indirect,
            incidental, or consequential damages, or for any loss of data, arising from your use of
            the app. Keep your own backups of anything important.
          </p>
        </Section>

        <Section icon={RefreshCw} title="Changes">
          <p>
            These terms may be updated over time. Material changes will be reflected by updating the
            date above. Continued use after a change means you accept the revised terms.
          </p>
        </Section>

        <Section icon={Mail} title="Contact">
          <p>
            Questions about these terms? Reach out at{" "}
            <a className="text-accent hover:underline" href={`mailto:${CONTACT_EMAIL}`}>
              {CONTACT_EMAIL}
            </a>
            .
          </p>
        </Section>
      </Card>

      <footer className="flex flex-wrap items-center gap-x-4 gap-y-2 text-sm text-ink-mute">
        <Link className="text-accent hover:underline" href="/privacy">
          Privacy Policy
        </Link>
        <span className="text-line">·</span>
        <Link className="text-accent hover:underline" href="/">
          Back to Musemint
        </Link>
      </footer>
    </div>
  );
}
