import { getProvider } from "./provider";
import { slugify } from "../utils";

export interface BuildPackInput {
  projectTitle: string;
  whyItMatters: string;
  sourceItems: { title: string; summary?: string | null; url?: string | null }[];
  techStack: string[];
  difficulty: string;
}

export interface BuildPack {
  overview: string;
  problemStatement: string;
  userStories: string[];
  features: string[];
  techStack: string[];
  architecture: string;
  apiPlan: { method: string; path: string; description: string }[];
  databaseSchema: { entity: string; fields: string[] }[];
  uiScreens: string[];
  tasks: string[];
  prompts: string[];
  readme: string;
  resumeBullets: string[];
}

const SYSTEM = `You are RecallOS, an elite product engineer. Produce a build pack as JSON with this shape:
{
 "overview": string,
 "problemStatement": string,
 "userStories": string[],
 "features": string[],
 "techStack": string[],
 "architecture": string,
 "apiPlan": [{"method": "GET|POST|PATCH|DELETE", "path": string, "description": string}],
 "databaseSchema": [{"entity": string, "fields": string[]}],
 "uiScreens": string[],
 "tasks": string[],
 "prompts": string[],
 "readme": string,
 "resumeBullets": string[]
}`;

function fallbackPack(input: BuildPackInput): BuildPack {
  const slug = slugify(input.projectTitle);
  const stack = input.techStack.length
    ? input.techStack
    : ["Next.js", "TypeScript", "Tailwind", "Prisma", "SQLite", "OpenAI / Gemini"];
  return {
    overview: `${input.projectTitle} — ${input.whyItMatters}. Built as a portfolio-grade ${input.difficulty.toLowerCase()} project synthesizing ${input.sourceItems.length} saved sources.`,
    problemStatement: `Builders constantly lose context across saved videos, posts, and links. ${input.projectTitle} closes that gap by transforming saved content into shipping work — a focused vertical of RecallOS.`,
    userStories: [
      "As a builder, I can capture any link or note in under 5 seconds.",
      "As a builder, I can see one AI-ranked action per item.",
      "As a builder, I can generate a project brief from a cluster of saves.",
      "As a builder, I can export the brief as README, JSON, or checklist.",
    ],
    features: [
      "Universal capture with auto-classification",
      "AI inbox triage with usefulness / actionability scoring",
      "Project idea generator from clustered saves",
      "Build pack exporter (README / JSON / checklist)",
      "Memory graph with category clusters",
      "Reminder engine for forgotten items",
    ],
    techStack: stack,
    architecture: `Next.js App Router + RSC for the UI. Prisma + SQLite for local persistence. A pluggable AI provider layer (Gemini → OpenAI → Anthropic → Groq → mock). Capture API normalizes input from share-sheet, browser extension, and pasted URL into a single CapturedItem.`,
    apiPlan: [
      { method: "POST", path: "/api/capture", description: "Create a captured item" },
      { method: "POST", path: "/api/items/:id/process", description: "Run AI processing" },
      { method: "POST", path: "/api/items/:id/project", description: "Spawn a project idea" },
      { method: "POST", path: "/api/projects/:id/build-pack", description: "Generate a build pack" },
      { method: "GET", path: "/api/search?q=", description: "Search captured memory" },
    ],
    databaseSchema: [
      { entity: "CapturedItem", fields: ["id", "kind", "title", "summary", "tags", "scores"] },
      { entity: "ProjectIdea", fields: ["id", "title", "sourceItems", "githubScore"] },
      { entity: "BuildPack", fields: ["id", "projectId", "markdown", "readme", "checklist"] },
    ],
    uiScreens: [
      "Dashboard with daily summary",
      "Universal capture modal",
      "AI inbox triage",
      "Ready to build grid",
      "Build pack detail",
    ],
    tasks: [
      "Scaffold Next.js + Prisma + Tailwind",
      "Implement /api/capture with Zod validation",
      "Wire the AI provider abstraction",
      "Build inbox triage page",
      "Build the build pack generator",
      "Add Playwright smoke tests",
    ],
    prompts: [
      "Summarize this saved item and score its actionability.",
      "Generate a SaaS landing page brief for this idea.",
      "Improve this prompt for clarity and reuse.",
    ],
    readme: `# ${input.projectTitle}\n\n${input.whyItMatters}\n\n## Stack\n${stack.map((s) => `- ${s}`).join("\n")}\n\n## Run\n\`\`\`bash\nnpm install\nnpm run db:push\nnpm run db:seed\nnpm run dev\n\`\`\`\n\nGenerated by RecallOS · /${slug}`,
    resumeBullets: [
      `Designed and shipped ${input.projectTitle}, an AI system that converts saved content into builder-ready briefs.`,
      `Built pluggable AI provider layer (Gemini / OpenAI / Anthropic / Groq) with deterministic mock fallback for offline dev.`,
      `Implemented end-to-end TypeScript stack with Next.js App Router, Prisma, and Playwright smoke tests.`,
    ],
  };
}

export async function generateBuildPack(input: BuildPackInput): Promise<{ pack: BuildPack; provider: string }> {
  const provider = await getProvider();
  if (provider.name === "mock") return { pack: fallbackPack(input), provider: "mock" };
  try {
    const userPrompt = [
      `Project title: ${input.projectTitle}`,
      `Why it matters: ${input.whyItMatters}`,
      `Difficulty: ${input.difficulty}`,
      `Preferred tech stack: ${input.techStack.join(", ") || "(open)"}`,
      `Source items:`,
      ...input.sourceItems.map(
        (s, i) => `  ${i + 1}. ${s.title}${s.summary ? ` — ${s.summary}` : ""}${s.url ? ` (${s.url})` : ""}`,
      ),
    ].join("\n");
    const res = await provider.complete({ system: SYSTEM, user: userPrompt, json: true });
    const parsed = JSON.parse(res.text);
    const merged = { ...fallbackPack(input), ...parsed };
    return { pack: merged, provider: provider.name };
  } catch (err) {
    console.warn("[ai] generateBuildPack fallback:", err);
    return { pack: fallbackPack(input), provider: "mock" };
  }
}

export function packToMarkdown(title: string, pack: BuildPack): string {
  const md: string[] = [];
  md.push(`# ${title}`);
  md.push(`\n${pack.overview}`);
  md.push(`\n## Problem statement\n${pack.problemStatement}`);
  md.push(`\n## User stories`);
  pack.userStories.forEach((s) => md.push(`- ${s}`));
  md.push(`\n## Features`);
  pack.features.forEach((s) => md.push(`- ${s}`));
  md.push(`\n## Tech stack`);
  pack.techStack.forEach((s) => md.push(`- ${s}`));
  md.push(`\n## Architecture\n${pack.architecture}`);
  md.push(`\n## API plan`);
  pack.apiPlan.forEach((a) => md.push(`- \`${a.method}\` \`${a.path}\` — ${a.description}`));
  md.push(`\n## Database schema`);
  pack.databaseSchema.forEach((d) =>
    md.push(`- **${d.entity}** — ${d.fields.join(", ")}`),
  );
  md.push(`\n## UI screens`);
  pack.uiScreens.forEach((s) => md.push(`- ${s}`));
  md.push(`\n## Tasks`);
  pack.tasks.forEach((s) => md.push(`- [ ] ${s}`));
  md.push(`\n## Prompts`);
  pack.prompts.forEach((s) => md.push(`- ${s}`));
  md.push(`\n## Resume bullets`);
  pack.resumeBullets.forEach((s) => md.push(`- ${s}`));
  return md.join("\n");
}

export function packToChecklist(pack: BuildPack): string {
  return pack.tasks.map((t) => `- [ ] ${t}`).join("\n");
}
